<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class PaymentOptionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //payment_type value will be WEB_VIEW if payment gateway flow is like complete web view and
        // it is mandatory to pass it in case of web view,other wise no need to add this key
        $arr_payment_options = [
            ['slug' => 'STRIPE', 'name' => 'Stripe', 'params' => '{"api_secret_key": "Secret Key","api_public_key": "Public Key","auth_token":"Customer Account Id"}'],
            ['slug' => 'PAYTM', 'name' => 'PAYTM', 'params' => '{"api_secret_key": "Merchant ID","api_public_key": "Merchant Key","callback_url": "Call back URL"}'],
            ['slug' => 'KORBA', 'name' => 'Korba', 'params' => '{"api_secret_key": "HMAC SECRET KEY","api_public_key": "HMAC CLIENT KEY","auth_token": "Client Id",callback_url": "Call back URL"}',],
            ['slug' => 'MPESA', 'name' => 'M-Pesa', 'params' => '{"api_secret_key": "Consumer Secret","api_public_key": "Consumer Key","auth_token": "PassKey","operator": "Short Code","tokenization_url": "Transaction Type (Ex : CustomerPayBillOnline)"}'],
            ['slug' => 'CC-AVENUE', 'name' => 'CC-AVENUE', 'params' => NULL,],
            ['slug' => 'RAZORPAY', 'name' => 'RAZORPAY', 'params' => '{"api_public_key": "Key Id","api_secret_key": "Secret Key"}'],
            //['slug' => 'SENANGPAY','name' => 'SENANGPAY','params' => '{"api_secret_key": "Secret Key","api_public_key": "Public Key","auth_token": "Authorization token","tokenization_url": "Token generation URL","payment_redirect_url": "Redirection URL","callback_url": "Call back URL"}'],
            ['slug' => 'SENANGPAY', 'name' => 'SENANGPAY', 'params' => '{"auth_token": "Authorization Token","api_secret_key": "Secret Key","tokenization_url": "Token generation URL","payment_redirect_url": "Payment URL","gateway_condition": "Gateway Condition"}'],
            ['slug' => 'MEPS', 'name' => 'MEPS', 'params' => '{"api_secret_key": "Secret Key","api_public_key": "Public Key","tokenization_url": "Token generation URL","payment_redirect_url": "Redirection URL","callback_url": "Call back URL" }'],
            ['slug' => 'BANCARD', 'name' => 'BANCARD', 'params' => '{"api_secret_key": "Secret Key","api_public_key": "Public Key","tokenization_url": "Token generation URL","payment_redirect_url": "Redirection URL","callback_url": "Call back URL"}'],
            ['slug' => 'PAYSTACK', 'name' => 'PAYSTACK', 'params' => '{"api_secret_key": "Secret Key","api_public_key": "Public Key","payment_redirect_url": "Transaction Charge URL"}'],
            ['slug' => 'PEACHPAYMENT', 'name' => 'PEACHPAYMENT', 'params' => '{"api_secret_key": "Entity ID","auth_token": "Authorization token","tokenization_url": "Prepare Checkout URL","payment_redirect_url":"Payment Redirect URL"}'],
            ['slug' => 'PAYPAL', 'name' => 'PAYPAL', 'params' => '{"api_secret_key": "Secret Key","api_client_key": "Client Key","auth_token" : "Currency exchange Key"}'],
            ['slug' => 'SSL COMMERCE', 'name' => 'SSL COMMERCE', 'params' => NULL],
            ['slug' => 'CIELO', 'name' => 'CIELO', 'params' => '{"api_secret_key": "Merchant Key","api_public_key": "Merchant Id","payment_redirect_url": "Transaction Charge URL","tokenization_url": "Tokenization URL"}'],
            ['slug' => 'BRAINTREE', 'name' => 'BRAINTREE', 'params' => '{"api_secret_key": "Private Key","api_public_key": "Public Key","auth_token": "Merchant_id"}'],
            ['slug' => 'IUGU', 'name' => 'IUGU', 'params' => '{"api_secret_key": "Api Secret Key","auth_token": "Account ID" }'],
            ['slug' => 'MERCADO', 'name' => 'MERCADO', 'params' => '{"api_secret_key": "Access Token","api_public_key": "App Key"}'],
            ['slug' => 'DPO', 'name' => 'DPO', 'params' => '{"api_secret_key": "Company Token","api_public_key": "Service Types","auth_token": "Company Reference"}'],
            ['slug' => 'BEYONICMOBILE', 'name' => 'BEYONICMOBILE', 'params' => '{"api_secret_key": "API Key","api_public_key": "Account Number"}'],
            ['slug' => 'FLUTTERWAVE', 'name' => 'FLUTTERWAVE', 'params' => '{"api_secret_key": "API Key","api_public_key": "Account Number","auth_token": "Encrypted Key"}'],
            //
            ['slug' => 'PAYU', 'name' => 'PAYU', 'params' => '{"api_secret_key": "Api Login","api_public_key": "Api Key","auth_token"=>"Account ID","payment_step"=>"2","operator":"Merchant Id"}'], //,""=>"PayU Merchant ID"// payment will be done in 2 steps Authorization, capture

            ['slug' => 'HYPERPAY', 'name' => 'HYPERPAY', 'params' => '{"api_secret_key": "HYPERPAY Entity ID","auth_token": "HYPERPAY Authorization token","tokenization_url": "Prepare Checkout URL","payment_redirect_url":"Payment Redirect URL"}'],
            ['slug' => 'BAYARIND', 'name' => 'BAYARIND', 'params' => '{"api_secret_key": "Secret Key","api_public_key": "Merchant ID","tokenization_url": "Prepare Checkout URL"}'],
            ['slug' => 'PAGADITO', 'name' => 'Pagadito', 'params' => '{"api_secret_key": "Pagadito UID","auth_token": "Pagadito    WSK"}'],
            ['slug' => 'MONERIS', 'name' => 'Moneris', 'params' => '{"api_secret_key": "Moneris Store Id","auth_token": "Moneris API Token"}'],
            ['slug' => 'EZYPOD', 'name' => 'EZYPOD', 'params' => '{"api_secret_key": "EZYPOD API Key","api_public_key": "EZYPOD Login Id","payment_redirect_url": "EZYPOD Payment Url"}'],
            ['slug' => 'CONEKTA', 'name' => 'CONEKTA', 'params' => '{"api_secret_key": "CONEKTA API Key","api_public_key": "CONEKTA Login Id","payment_redirect_url": "CONEKTA Payment Url"}'],
            // payment gateway name is ozow by mistaken its written its as ozow
            ['slug' => 'OZOH', 'name' => 'Ozow Instant EFT(Mobile SDK)', 'params' => '{"api_secret_key": "OZOW Private Key","api_public_key": "OZOW Api Key","auth_token":"Merchant Code"}'],
            ['slug' => 'FLUTTERWAVE', 'name' => 'FLUTTERWAVE', 'params' => '{"api_secret_key": "FLUTTERWAVE API Key","api_public_key": "FLUTTERWAVE"}'],
            ['slug' => 'YOPayments', 'name' => 'YO-Uganda', 'params' => '{"api_secret_key": "API Password","api_public_key": "API Username"}'],
            ['slug' => 'MaxiCash', 'name' => 'MaxiCash', 'params' => '{"user_name": "","password": ""}'],
            ['slug' => 'TELR', 'name' => 'TELR', 'params' => '{"api_secret_key": "TELR API Key","api_public_key": "TELR"}'],
            ['slug' => 'IllicoCash', 'name' => 'IllicoCash', 'params' => '{"api_secret_key": "LoginName","api_public_key": "LoginPass","auth_token": "Basic Authorization token","additional_data":"Additional Data Json ({merchantid:?,terminalid:?,encryptkey:?})"}'],
            ['slug' => 'TriPay', 'name' => 'TriPay', 'params' => '{"api_secret_key": "Api Key","api_public_key": "Private Key","auth_token": "Merchant Code","gateway_condition":"Gateway Condition(1-Live, 2-Test)"}'],
            ['slug' => 'BOOKEEY', 'name' => 'BOOKEEY', 'params' => '{"api_secret_key": "BOOKEEY Secret Key","api_public_key": "BOOKEEY Merchant UID"}'],
            ['slug' => 'CinetPay', 'name' => 'CinetPay', 'params' => '{"api_secret_key": "Cinetpay App Key","api_public_key": "Cinetpay Site Key"}'],
            ['slug' => 'PayGate', 'name' => 'PayGate', 'params' => '{"api_secret_key": "Paygate Password","api_public_key": "Paygate ID "}'],
            ['slug' => 'PAYPHONE', 'name' => 'PayPhone', 'params' => '{"api_secret_key": "PayPhone Token","api_public_key": "Customer ID "}'],
            ['slug' => 'AAMARPAY', 'name' => 'aamarPay', 'params' => '{"api_secret_key": "Secret key","api_public_key": "Store ID "}'],
            ['slug' => 'MOMOPAY', 'name' => 'MOMOPay', 'params' => '{"api_public_key": "MOMOPay Api User ID ","api_secret_key": "MOMOPay Api User key","auth_token": "MOMOPay Subscription Key"}'],
            ['slug' => 'EDAHAB', 'name' => 'E-Dahab', 'params' => '{"api_secret_key": "Secret key","api_public_key": "Public Key","auth_token":"Agent Code"}'],
            ['slug' => 'TELEBIRR', 'name' => 'Telebirr', 'params' => '{"api_secret_key": "Secret key","api_public_key": "Public Key"}'],
            ['slug' => 'PAYBOX', 'name' => 'PayBox', 'params' => '{"api_secret_key": "Secret key","api_public_key": "Public Key"}'],
            ['slug' => 'CASHFREE', 'name' => 'CashFree', 'params' => '{"api_secret_key": "Secret key","api_public_key": "App ID "}'],
            ['slug' => 'PROXYPAY', 'name' => 'ProxyPay', 'params' => '{"api_secret_key": "Api Key","api_public_key": "Entity Code"}'],
            ['slug' => 'PAYFAST', 'name' => 'PayFast', 'params' => '{"api_secret_key": "Secret key","api_public_key": "public key ","additional_data":"Additional Data Json ({sandbox_url:?,live_url:?})"}'],
            ['slug' => 'PAYMAYA', 'name' => 'PayMaya', 'params' => '{"api_secret_key": "Secret Key","api_public_key": "Public Key"}'],
            ['slug' => 'PAYHERE', 'name' => 'PayHere', 'params' => '{"api_secret_key": "Merchant Secret","api_public_key": "Merchant Id", "auth_token": "Auth Code(Base64encode(App Id:App Secret))"}'],
            ['slug' => 'SDGEXPRESS', 'name' => 'SDGEXPRESS', 'params' => '{"api_secret_key": "Secret/Password","api_public_key": "Public/User name"}'],
            ['slug' => 'MERCADOCARD', 'name' => 'Mercado Card', 'params' => '{"api_secret_key": "Access Token","api_public_key": "App Key"}'],
            ['slug' => 'MERCADOPIX', 'name' => 'Mercado Bank Transfer', 'params' => '{"api_secret_key": "Access Token","api_public_key": "App Key"}'],
            ['slug' => 'COVERAGEPAY', 'name' => 'Coverage card Payment', 'params' => '{"api_secret_key": " SSL User Pin","api_public_key": "SSL user ID","auth_token": "SSL merchant ID"}'],
            ['slug' => 'ZAAD', 'name' => 'ZAAD ', 'params' => '{"api_secret_key": " Private Key","api_public_key": "Public Key","auth_token": "Auth token"}'],
            ['slug' => 'PAYGATEGLOBAL', 'name' => 'PaygateGlobal ', 'params' => '{"api_secret_key": " Private Key","api_public_key": "Public Key","auth_token": "Auth token"}'],
            ['slug' => 'SQUARE', 'name' => 'Square ', 'params' => '{"api_secret_key": " Private Key"}'],
            ['slug' => 'TOUCHPAY', 'name' => 'Touch Pay ', 'params' => '{"api_secret_key": " Private Key","api_public_key": " Public Key","auth_token": "Auth Token","additional_data": "data in josn format"}'],
            ['slug' => 'CLOVER', 'name' => 'CLOVER ', 'params' => '{"api_secret_key": " Private Token","api_public_key": "Public Token"}'],
            ['slug' => 'KUSHKI', 'name' => 'KUSHKI ', 'params' => '{"api_secret_key": " Private Token","api_public_key": "Public Token"}'],
            ['slug' => 'OPAY', 'name' => 'OPAY ', 'params' => '{"api_secret_key": " Api Secret Key","api_public_key": "Public Key","auth_token": " Merchant ID"}'],
            ['slug' => 'PAYGATEGLOBAL', 'name' => 'PayGateGlobal ', 'params' => '{"api_secret_key": " API Key"}'],
            ['slug' => 'PINPAYMENT', 'name' => 'Pin Payments', 'params' => '{"api_secret_key": "Secret Key","api_public_key": "Publishable Key"}'],
            ['slug' => 'PAGUELO_FACIL', 'name' => 'Paguelo Facil', 'params' => '{"api_secret_key": "CCLW Token","api_public_key": "Authorization Token"}'],
            ['slug' => 'PAGOPLUX', 'name' => 'Pagoplux', 'params' => '{"api_secret_key": "PagoPlux Secret password","api_public_key": "PagoPlux Customer ID","auth_token": "PayBoxClientIdentification","tokenization_url": "PagoPlux Email","payment_redirect_url":"PayboxIdPlan"}'],
            ['slug' => 'WEBXPAY', 'name' => 'Webxpay', 'params' => '{"api_secret_key": "Secret Key","api_public_key": "Public Key"}'],
            ['slug' => 'INTERSWITCH', 'name' => 'Interswitch', 'params' => '{"api_secret_key": "Password","api_public_key": "Username", "auth_token": "ClientID:SecretKey"}'],
            ['slug' => 'TELEBIRRPAY', 'name' => 'Telebirr Pay', 'params' => '{"api_secret_key": "Telebirr App Key","api_public_key": "Telebirr App ID","auth_token": "Telebirr Public Key","tokenization_url": "Telebirr ShortCode","payment_redirect_url":"H5 URL"}'],
            ['slug' => 'ORANGEMONEY_WEB', 'name' => 'ORANGEMONEY_WEB', 'params' => '{"api_public_key":"Merchant Key","auth_token": "ORANGEMONEY Auth Token","operator":"Country Code By Pg"}'],
            ['slug' => 'IHELA', 'name' => 'iHela', 'params' => '{"api_public_key": "iHela ClientId","api_secret_key": "iHela Client Secret"}'],
            ['slug' => 'BILLBOX', 'name' => 'BillBox', 'params' => '{"api_public_key": "BillBox App Reference","api_secret_key": "BillBox Secret","auth_token": "BillBox AppId"}'],
            ['slug' => 'SAMPAY', 'name' => 'Sampay', 'params' => '{"api_public_key": "Api Key","auth_token": "Auth Key"}'],
            ['slug' => 'PAYGO', 'name' => 'PayGo', 'params' => '{"api_public_key": "User Name","api_secret_key": "Password","auth_token":"Client ID"}'],
            ['slug' => 'KPAY', 'name' => 'KPay', 'params' => '{"api_public_key": "User Name","api_secret_key": "Password","auth_token":"Retailer ID"}'],
            ['slug' => 'POWERTRANZ', 'name' => 'POWERTRANZ', 'params' => '{"api_secret_key": "Password","api_public_key": "Username"}'],
            ['slug' => 'EVMAK', 'name' => 'EvMak', 'params' => '{"api_public_key": "Project Name","api_secret_key": "EvMak Username"}'],
            ['slug' => 'MIPS', 'name' => 'MIPS', 'params' => '{"api_public_key": "Username","api_secret_key": "Password","additional_data":"Additional Data Json ({id_merchant:?,id_entity:?,operator_id:?,remote_user_password:?,cipher_key:?,salt:?})"}'],
            ['slug' => 'GLOMO_MONEY', 'name' => 'Glomo Money', 'params' => '{}'],
            ['slug' => 'PAYSTACK_WEBVIEW', 'name' => 'PAYSTACK Webview', 'params' => '{"api_secret_key": "Secret Key","api_public_key": "Public Key","payment_redirect_url": "Transaction Charge URL"}'],
            ['slug' => 'EBANKILY', 'name' => 'EBankily', 'params' => '{"api_secret_key": "Password","api_public_key": "Username","auth_token": "Client ID"}'],
            ['slug' => 'PAYRIFF', 'name' => 'Payriff', 'params' => '{"api_secret_key": "Application Secret Key","api_public_key": "Application Merchant Code"}'],
            ['slug' => 'PAYRIFF_CARD_SAVE', 'name' => 'Payriff (Card Save)', 'params' => '{"api_secret_key": "Application Secret Key","api_public_key": "Application Merchant Code"}'],
            ['slug' => 'WAVE', 'name' => 'Wave', 'params' => '{"api_secret_key": "Wave Api Key"}'],
            ['slug' => 'HUBTEL_WEBVIEW', 'name' => 'Hubtel (Webview)', 'params' => '{"api_secret_key": "App Key","api_public_key": "App ID","auth_token":"Merchant Account Number"}'],
            ['slug' => 'WAAFI', 'name' => 'waafi', 'params' => '{"api_secret_key": "merchantUid Secret Key","api_public_key": "hppKey Public Key","auth_token":"Store Id"}'],
            ['slug' => 'PAYPAY','name' => 'PAYPAY','params' => '{"api_public_key": "RSA public Key","api_secret_key": "RSA private Key","auth_token":"PAYPAY Public Key","additional_data":"Additional Data Json ({partner_id:?,sales_product_code:?})"}'],
            ['slug' => 'SAHAY','name' => 'Sahay','params' => '{"api_public_key": "Consumer Key","api_secret_key": "Consumer Secret"}'],
            ['slug' => 'MIDTRANS_MOBILE_SDK','name' => 'Midtrans Mobile SDK','params' => '{"api_public_key": "Server Key"}'],
            ['slug' => 'YOCO','name' => 'Yoco(Webview)','params' => '{"api_public_key": "Public Key","api_secret_key": "Secret Key"}'],
            ['slug' => 'ONE_VISION','name' => 'OneVision','params' => '{"api_public_key": "Public Key","api_secret_key": "Secret Key"}'],
            ['slug' => 'ONE_VISION_CASHOUT','name' => 'OneVision For Cashout','params' => '{"api_public_key": "Public Key","api_secret_key": "Secret Key"}'],
            ['slug' => 'TINGG','name' => 'TINGG','params' => '{"api_public_key": "Tingg ivKey","api_secret_key": "Tingg Secret Key","auth_token":"Tingg Access Key","operator":"Service Code"}'],
            ['slug' => 'VIU_PAY', 'name' => 'ViuPay', 'params' => '{"api_public_key": "Client ID","api_secret_key": "Client Secret"}'],
            ['slug' => 'CASH_PAY', 'name' => 'CashPay', 'params' => '{"api_public_key": "Client/Login ID","api_secret_key": "API Key"}'],
            ['slug' => 'PESAPAL', 'name' => 'Pesapal', 'params' => '{"api_public_key": "Consumer Key","api_secret_key": "Consumer Secret Key"}'],
            ['slug' => 'TAP', 'name' => 'TAP', 'params' => '{"api_public_key": "Public Key","api_secret_key": "Secret Key"}'],
            ['slug' => 'PAYWEB3', 'name' => 'PAYWEB3 (PAYGATE)', 'params' => '{"auth_token": "PAYWEB3 PayGate Id","api_secret_key": "Encryption Key"}'],
            ['slug' => 'HUB_2', 'name' => 'Hub2', 'params' => '{"api_public_key": "Merchant ID","api_secret_key": "API Key"}'],
            ['slug' => 'UNIWALLET','name' => 'Uniwallet','params' => '{"api_secret_key": "Api Key","api_public_key": "Merchant ID", "auth_token": "Product ID", "tokenization_url": "Payment Gateway Base URL"}'],
            ['slug' => 'WIPAY', 'name' => 'WiPay', 'params' => '{"api_public_key": "Account Number","api_secret_key": "API Key"}'],
            ['slug' => 'AZAMPAY', 'name' => 'AzamPay', 'params' => '{"api_public_key": "App Name","api_secret_key": "Client id","auth_token": "Client Secret"}'],
            ['slug' => 'ORANGEMONEY', 'name' => 'Orange Money', 'params' => '{"api_public_key": "Client Id","api_secret_key": "Client Secret","auth_token":"Merchant Code","additional_data":"Additional Data Json ({merchant_payout_phone:?,merchant_pin:?})"}'],
            ['slug' => 'SERFINSA', 'name' => 'Serfinsa', 'params' => '{"api_public_key": "Com Id","api_secret_key": "Com Key","auth_token":"Com Workstation","operator":"Terminal ID","tokenization_url":"Trade ID"}'],
            ['slug' => 'SMARTPAY', 'name' => 'SmartPay', 'params' => '{"auth_token":"Merchant User Id"}'],
            ['slug' => 'PESEPAY', 'name' => 'Pesepay', 'params' => '{"auth_token":"Integration Key","api_secret_key": "Encryption Key"}', 'payment_type' => 'WEB_VIEW'],
            ['slug' => 'ORANGEMONEY_PUSH', 'name' => 'Orange Money Push', 'params' => '{"auth_token":"Merchant MSISDN","api_public_key":"Username","api_secret_key": "Password"}'],
            ['slug' => 'UNI5PAY','name' => 'Uni5Pay', 'params'=> '{"api_public_key": "Uni5Pay Api Key"}'],
            ['slug' => 'TRANZAK','name' => 'Tranzak', 'params'=> '{"api_public_key": "App Id","api_secret_key": "App Key"}'],
            ['slug' => 'AIRTEL','name' => 'Airtel', 'params'=> '{"api_public_key": "Client Id","api_secret_key": "Client Secret Key"}'],
            ['slug' => 'PAYAW','name' => 'Payaw', 'params'=> '{"api_public_key": "Api Key","api_secret_key": "Secret Key"}'],
            ['slug' => 'CXPAY','name' => 'CXPAY', 'params'=> '{api_secret_key": "Api Key"}'],
            ['slug' => 'WAAFIPAY', 'name' => 'WAAFIPAY_NEW', 'params' => '{"api_secret_key": "merchantUid Secret Key","api_public_key": "Api Key Public Key","auth_token":"Store Id"}'],
            ['slug' => 'BOGPAY', 'name' => 'BOGPAY', 'params' => '{"api_public_key": "Client Id","api_secret_key": "Client Secret Key"}'],
            ['slug' => 'PAYNOW', 'name' => 'PAYNOW', 'params' => '{"api_secret_key": "Integeration Key","api_public_key": "Integeration Id"}'],
            ['slug' => 'FASTHUB', 'name' => 'FASTHUB', 'params' => '{"api_public_key": "Client Username","api_secret_key": "Client Password", "auth_token": "Client Pre Shared Key" }'],
            ['slug' => 'CACPAY', 'name' => 'CACPAY', 'params' => '{"api_public_key": "Client Username","api_secret_key": "Client Password","operator":"app key","auth_token":"api key","additional_data":"Company Service ID"}'],
            ['slug' => 'PEACH_SERVER_TO_SERVER', 'name' => 'PEACH_SERVER_TO_SERVER', 'params' => '{"api_public_key": "Entity ID", "auth_token":"Access Token"}'],
            ['slug' => 'DIBSYPAYMENT', 'name' => 'DIBSYPAYMENT', 'params' => '{"api_secret_key": "Secret Key","api_public_key": "Public key"}'],
            ['slug' => 'MGURUSH', 'name' => 'MGURUSH', 'params' => '{"api_secret_key": "Secret Key","api_public_key": "Access key"}'],
            ['slug' => 'ORANGEMONEYCORE', 'name' => 'ORANGEMONEYCORE', 'params' => '{"api_public_key": "Username","api_secret_key": "Password","operator": "Pin","auth_token":"X-Auth-Token","additional_data":"Channel User Msisdn"}'],
            ['slug' => 'CRDB', 'name' => 'CRDB', 'params' => '{"api_public_key": "profile_id","api_secret_key": "access_key", "auth_token":"Secret Key"}', "payment_type" => "WEB_VIEW"],
            ['slug' => 'TELEBIRRPAY_NEW', 'name' => 'TELEBIRR PAY NEW', 'params' => '{"api_secret_key": "Telebirr App Secret Key","api_public_key": "Telebirr Merchant App ID","auth_token": "Telebirr Fabric App Id","tokenization_url": "Telebirr ShortCode","payment_redirect_url":"H5 URL"}'],
            ['slug' => 'MAXICASH', 'name' => 'MAXICASH', 'params' => '{"api_secret_key": "MERCHANT ID","api_public_key": "MERCHANT PASSWORD"}'],
            ['slug' => 'KHALTI', 'name' => 'KHALTI', 'params' => '{"api_secret_key": "Secret Key","api_public_key": "Public key"}'],
            ['slug' => 'ORANGE_MONEY_B2B', 'name' => 'ORANGE_MONEY_B2B', 'params' => '{"auth_token": "ORANGE_MONEY_B2B Auth Token", "api_secret_key": "posId"}'],
            ['slug' => 'BINANCE', 'name' => 'BINANCE','params' => '{"api_public_key": "Username","api_secret_key": "Password"}'],
            ['slug' => 'TAP_PAYMENT', 'name' => 'TAP_PAYMENT', 'params' => '{"api_public_key": "Public Key","api_secret_key": "Secret Key"}'],
            ['slug' => 'PAWAPAY', 'name' => 'PAWAPAY', 'params' => '{"api_secret_key": "Api Token"}'],
            ['slug' => 'FLUTTERWAVE_STANDARD', 'name' => 'FLUTTERWAVE STANDARD', 'params' => '{"api_secret_key": "FLUTTERWAVE STANDARD Secret Key"}', 'payment_type' => 'WEB_VIEW'],
            ['slug' => 'LIGDICASH', 'name' => 'LIGDICASH PAYMENTS', 'params' => '{"api_secret_key": "Ligdicash api key", "auth_token": "Ligdi Cash Bearer Token"}', 'payment_type' => 'WEB_VIEW'],
            ['slug' => 'REVOLUTPAY', 'name' => 'REVOLUTPAY', 'params' => '{"api_secret_key": "Secret Key"}'],
            ['slug' => 'UBPAY', 'name' => 'UBPAY', 'params' => '{"api_secret_key": "Merchant Id"}'],
            ['slug' => 'CASHPLUS', 'name' => 'CASHPLUS', 'params' => '{"api_public_key": "Merchant Code","api_secret_key": "Secret Key"}'],
            ['slug' => 'NETCASH', 'name' => 'NETCASH', 'params' => '{"api_public_key": "M2(Software Vendor Key)","api_secret_key": "M1(PayNow Service Key)"}'],
            ['slug' => 'IMBANK_MPESA', 'name' => 'IMBANK MPESA', 'params' => '{"api_public_key": "Application Id","api_secret_key": "Certificate Id"}'],
            ['slug' => 'ESEWA_PAY', 'name' => 'ESEWA PAY', 'params' => '{"api_public_key": "Product Code"}'],
            ['slug' => 'FLEX_PAY', 'name' => 'FLEX PAY', 'params' => '{"api_public_key": "Merchant Code","api_secret_key": "Api Key"}'],
            ['slug' => 'AUB_PAY', 'name' => 'AUB PAY', 'params' => '{"api_public_key": "merchant_id","auth_token":"Sign key"}'],
            ['slug' => 'S3P_PAY', 'name' => 'S3P Pay', 'params' => '{"api_public_key": "S3P KEY","api_secret_key": "S3P SECRET KEY"}'],
            ['slug' => 'EASY_PAY', 'name' => 'Easy Pay', 'params' => '{"api_secret_key": "Auth Key"}'],
            ['slug' => 'REMITA_PAY', 'name' => 'Remita Pay', 'params' => '{"api_public_key": "Merchant Id","api_secret_key": "API Key","auth_token": "Service Type Id"}'],
            ['slug' => 'MPESA_B2C', 'name' => 'MPESA B2C Payment', 'params' => '{"api_public_key": "Consumer Key","api_secret_key": "Consumer Secret Key","auth_token": "Initiator Name","additional_data":"Password","operator": "Short Code"}'],
            ['slug' => 'XENDIT_PAY', 'name' => 'XENDIT Payment', 'params' => '{"api_public_key": "Api Secret key","auth_token": "Webhook Secret Key"}'],
            ['slug' => 'WORLD_PAY', 'name' => 'World Pay', 'params' => '{"api_public_key": "UserName","api_secret_key": "Password","auth_token":"Entity"}'],
            ['slug' => 'SASA_PAY', 'name' => 'Sasa Pay', 'params' => '{"api_public_key": "UserName","api_secret_key": "Password"}'],
            ['slug' => 'GENIE_BUSINESS_PAY', 'name' => 'Genie business pay', 'params' => '{"api_public_key": "App key"}','payment_type' => 'WEB_VIEW'],
            ['slug' => 'PAYCHANGU', 'name' => 'PayChangu', 'params' => '{"api_secret_key": "Secret key"}','payment_type' => 'WEB_VIEW'],
            ['slug' => 'SERDI_PAY', 'name' => 'SerdiPay', 'params' => '{"api_public_key": "UserName","api_secret_key": "Password","auth_token":"Api Password","operator":"Api Id","additional_data":"Merchant Code","tokenization_url":"Merchant Pin"}','payment_type' => ''],
            ['slug' => 'UALABIS_PAY', 'name' => 'UALABIS_PAY', 'params' => '{"api_public_key": "User Name","api_secret_key":"Client Secret Id","auth_token":"client Id"}','payment_type' => 'WEB_VIEW'],
            ['slug' => 'SELCOM_PAY', 'name' => 'SELCOM_PAY', 'params' => '{"api_public_key": "Api Key","api_secret_key":"Api Secret Key","tokenization_url":"Payment Url","operator":"Vendor"}','payment_type' => ''],
            ['slug' => 'IKHOKHA_PAY', 'name' => 'IKHOKHA_PAY', 'params' => '{"api_public_key": "Application Key","api_secret_key":"Application Secret Key"}','payment_type' => 'WEB_VIEW'],
            ['slug' => 'MERCADO_SDK', 'name' => 'MERCADO_SDK', 'params' => '{"api_public_key": "Public Key","api_secret_key":"Access Token"}'],
            ['slug' => 'LENCOPAY', 'name' => 'LENCO_PAY', 'params' => '{"api_public_key": "Public Key","api_secret_key":"Secret Key"}','payment_type' => 'WEB_VIEW'],
            ['slug' => 'MODEMPAY', 'name' => 'MODEM_PAY', 'params' => '{"api_public_key": "Public Key","api_secret_key":"Secret Key","auth_token":"Webhook Hash/Secret Key"}','payment_type' => 'WEB_VIEW'],
            ['slug' => 'IP88_PAY', 'name' => 'IP88_PAY', 'params' => '{"api_public_key": "Public Key","api_secret_key":"Secret Key"}','payment_type' => ''],
            ['slug' => 'GEIDEA', 'name' => 'GEIDEA', 'params' => '{"api_secret_key": "API Secret Key","api_public_key": "Merchant Public Key"}','payment_type' => 'WEB_VIEW'],
            ['slug' => 'APIARY_FDI_PAYMENT', 'name' => 'APIARY FDI PAYMENT', 'params' => '{"api_secret_key": "App Secret","api_public_key": "App Id","auth_token":"Account Id"}','payment_type' => ''],
            ['slug' => 'MONNIFY', 'name' => 'MONNIFY PAYMENT', 'params' => '{"api_secret_key": "Contrat Code","api_public_key": "Api Key"}','payment_type' => 'WEB_VIEW'],
            ['slug' => 'ADD_PAY', 'name' => 'ADD PAY', 'params' => '{"api_secret_key": "Client Secret","api_public_key": "Client Id"}','payment_type' => 'WEB_VIEW'],
            ['slug' => 'CLICKPASEPAY', 'name' => 'CLICKPASEPAY', 'params' => '{"api_public_key": "Client Id","api_secret_key": "Api Key"}'],
            ['slug' => 'MYSAFARI', 'name' => 'MYSAFARI', 'params' => '{"callback_url": "Callback Url"}'],
            ['slug' => 'YASPAY', 'name' => 'YASPAY', 'params' => '{"api_secret_key": "Password","api_public_key": "Username"}'],
            ['slug' => 'DEBITO', 'name' => 'DEBITO', 'params' => '{"api_secret_key": "API Key","additional_data":"Wallet Ids Json ({e-mola:?,m-pesa:?,card:?})"}'],
            ['slug' => 'MOMOPAY_CASHOUT', 'name' => 'MOMOPAY CASHOUT', 'params' => '{"api_secret_key": "API Key","api_public_key":"Api User","auth_token":"Subscription Key","operator": "Environment"}'],
            ['slug' => 'XRPAY', 'name' => 'XRPAY', 'params' => '{"api_public_key":"Wallet Number"}'],
        ];

        foreach ($arr_payment_options as $key => $value) {
            DB::table('payment_options')->insert([
                'slug' => $value['slug'],
                'name' => $value['name'],
                'params' => $value['params'],
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ]);
        }
    }
}
