<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class SmsGatewaysTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $sms_gateways = array(
            array('name' => 'TWILLIO','params' => '{"api_key":"SID","sender_number":"Twillio Number","auth_token":"Auth Token"}','description' => 'twillio','status' => '1','environment' => NULL),
            array('name' => 'KUTILITY','params' => '{"api_key":"Public Key","sender":"Sender"}','description' => 'KUTILITY','status' => '1','environment' => NULL),
            array('name' => 'MobiReach','params' => '{"api_key":"Username","sender_number":"Sender","auth_token":"Password"}','description' => 'MobiReach','status' => '1','environment' => NULL),
            array('name' => 'AFRICATALKING','params' => '{"api_key":"Username","auth_token":"Password","sender":"Sender Id"}','description' => 'AFRICATALKING','status' => '1','environment' => NULL),
            array('name' => 'SENANGPAY','params' => '{"api_key":"Username","auth_token":"Password"}','description' => 'SENANGPAY','status' => '1','environment' => NULL),
            array('name' => 'ONEWAYSMS','params' => '{"api_key":"Username","sender":"Sender Id","auth_token":"Password","usermessage":"Enter User Message","drivermessage":"Enter Driver Message"}','description' => 'ONEWAYSMS','status' => '1','environment' => '1'),
            array('name' => 'KNOWLARITY','params' => '{"api_key":"Username","sender":"Sender Id","auth_token":"Password"}','description' => 'knowlarity','status' => '1','environment' => '1'),
            array('name' => 'ROUTESMS','params' => '{"api_key":"Username","sender":"Sender Id","auth_token":"Password"}','description' => 'RouteSms','status' => '1','environment' => '1'),
            array('name' => 'JAVNA','params' => '{"api_key":"Username","auth_token":"Password"}','description' => 'Javna','status' => '1','environment' => '1'),
            array('name' => 'EASYSENDSMS','params' => '{"api_key":"Username","sender":"Sender Id","auth_token":"Password"}','description' => 'EASYSENDSMS','status' => '1','environment' => '1'),
            array('name' => 'ROBISEARCH','params' => '{"api_key":"Username","auth_token":"Password","sender":"Sender Id"}','description' => 'Robisearch','status' => '1','environment' => '1'),
            array('name' => 'EXOTEL','params' => '{"api_key":"Exotel Sid","auth_token":"Exotel token","sender":"Sender Number"}','description' => 'EXOTEL','status' => '1','environment' => NULL),
            array('name' => 'TEXTLOCAL','params' => '{"api_key": "API Key", "sender": "Sender"}','description' => 'TEXTLOCAL','status' => '1','environment' => '1'),
            array('name' => 'CLICKATELL','params' => '{"api_key": "API Key"}','description' => 'CLICKATELL','status' => '1','environment' => NULL),
            array('name' => 'NEXMO','params' => '{"api_key": "API Key", "api_secret_key": "API Secret Key" }','description' => 'NEXMO','status' => '1','environment' => NULL),
            array('name' => 'SMSLIVE247','params' => '{"api_key": "Main Account Login Email","subacct":"Sub Account","auth_token": "Sub Password","sender":"Sender"}','description' => 'SMSLIVE247','status' => '1','environment' => NULL),
            array('name' => 'NRSGATEWAY','params' => '{"api_key": "Username", "auth_token": "Password","sender":"Sender"}','description' => 'NRSGATEWAY','status' => '1','environment' => NULL),
            array('name' => 'EASYSERVICE','params' => '{"api_key": "Api key", "sender":"Sender", "api_secret_key" : "Message Type"}','description' => 'EASYSERVICE','status' => '1','environment' => NULL),
            array('name' => 'DATASOFT','params' => '{ "api_key": "Username", "sender":"Sender","auth_token" : "Password" }','description' => 'DATASOFT','status' => '1','environment' => NULL),
            array('name' => 'CELLSYNT','params' => '{ "api_key": "Username", "sender":"Sender","auth_token" : "Password"}','description' => 'CELLSYNT','status' => '1','environment' => NULL),
            array('name' => 'SERVICIO','params' => '{"api_key": "Username","auth_token" : "Password" }','description' => 'SERVICIO','status' => '1','environment' => NULL),
            array('name' => 'SENDPULSE','params' => '{"api_key": "Client ID","sender":"Sender","auth_token" : "Client Secret","account_id":"Address Book ID"}','description' => 'SENDPULSE','status' => '1','environment' => NULL),
            array('name' => 'SMSCOUNTRY','params' => '{"api_key": "Username","sender":"Sender","auth_token" : "Password"}','description' => 'SMSCOUNTRY','status' => '1','environment' => NULL),
            array('name' => 'EBULKSMS','params' => '{ "api_key": "","sender":"SMASHRIDES", "auth_token" : "Password" }','description' => 'SMSCOUNTRY','status' => '1','environment' => NULL),
            array('name' => 'ENGAGE SPARK','params' => '{"api_key":"engageSPARK Organization ID","auth_token":"engageSPARK Authorization","sender":"engageSPARK Sender"}','description' => 'ENGAGE SPARK','status' => '1','environment' => NULL),
            array('name' => 'POSTAGUVERCINI','params' => '{"api_key":"POSTAGUVERCINI Username","auth_token":"POSTAGUVERCINI Password","sender":"POSTAGUVERCINI Sender"}','description' => 'POSTAGUVERCINI','status' => '1','environment' => NULL),
            array('name' => 'SMARTSMSSOLUTIONS','params' => '{"api_key":"SMARTSMSSOLUTIONS SenderId","auth_token":"SMARTSMSSOLUTIONS Token","sender":"SMARTSMSSOLUTIONS Sender"}','description' => 'SMARTSMSSOLUTIONS','status' => '1','environment' => NULL),
            array('name' => 'SMSVIRO','params' => '{"api_key":"SMSVIRO SenderId","auth_token":"SMSVIRO Token"}','description' => 'SMSVIRO','status' => '1','environment' => NULL),
            array('name' => 'AAKASHSMS','params' => '{"api_key":"AAKASHSMS SenderId","auth_token":"AAKASHSMS Token"}','description' => 'AAKASHSMS','status' => '1','environment' => NULL),
            array('name' => 'BULKSMSNIGERIA','params' => '{"api_key":"BULKSMSNIGERIA SenderId","auth_token":"BULKSMSNIGERIA Token"}','description' => 'BULKSMSNIGERIA','status' => '1','environment' => NULL),
            array('name' => 'BULKSMSZAMTEL','params' => '{"api_key":"BULKSMSZAMTEL Api Key","sender":"BULKSMSZAMTEL SenderId"}','description' => 'BULKSMSZAMTEL','status' => '1','environment' => NULL),
            array('name' => 'SSLWIRELESS','params' => '{"api_key":"SSLWIRELESS SenderId","auth_token":"SSLWIRELESS Username","api_secret_key":"SSLWIRELESS Password"}','description' => 'SSLWIRELESS','status' => '1','environment' => NULL),
            array('name' => 'MYTELESOM','params' => '{"api_key":"MYTELESOM Api Key","auth_token":"MYTELESOM Username","api_secret_key":"MYTELESOM Password","sender":"MYTELESOM Sender"}','description' => 'SSLWIRELESS','status' => '1','environment' => NULL),
            array('name' => 'SELCOMSMS','params' => '{"api_key":"SELCOMSMS Username","api_secret_key":"SELCOMSMS Password"}','description' => 'SELCOMSMS','status' => '1','environment' => NULL),
            array('name' => 'NSEMFUA','params' => '{"api_key":"NSEMFUA Api Key","sender":"NSEMFUA Sender"}','description' => 'NSEMFUA','status' => '1','environment' => NULL),
            array('name' => 'PLIVO','params' => '{"api_key":"PLIVO AuthId","auth_token":"PLIVO Auth Token","sender":"PLIVO Sender"}','description' => 'PLIVO','status' => '1','environment' => NULL),
            array('name' => 'BULKSMSBD','params' => '{"api_key":"BULKSMSBD Username","auth_token":"BULKSMSBD Password"}','description' => 'BULKSMSBD','status' => '1','environment' => NULL),
            array('name' => 'MULTITEXTER','params' => '{"api_key":"MULTITEXTER Username","auth_token":"MULTITEXTER Password","sender":"MULTITEXTER Sender"}','description' => 'MULTITEXTER','status' => '1','environment' => NULL),
            array('name' => 'MSG91','params' => '{"auth_token":"MSG91 AuthKey","sender":"MSG91 Sender"}','description' => 'MSG91','status' => '1','environment' => NULL),
            array('name' => 'OUTREACH','params' => '{"api_key":"OUTREACH Username","auth_token":"OUTREACH Password","sender":"OUTREACH Masking"}','description' => 'OUTREACH','status' => '1','environment' => NULL),
            array('name' => 'BUDGETSMS','params' => '{"api_key":"BUDGETSMS Username","auth_token":"BUDGETSMS Handle","sender":"BUDGETSMS SenderId","api_secret_key" : "BUDGETSMS UserId"}','description' => 'BUDGETSMS','status' => '1','environment' => NULL),
            array('name' => 'CLICKATELLAPI','params' => '{"api_key":"CLICKATELLAPI Username","api_secret_key":"CLICKATELLAPI Password","sender":"CLICKATELLAPI ApiId"}','description' => 'CLICKATELLAPI','status' => '1','environment' => NULL),
            array('name' => 'SHAMELSMS','params' => '{"api_key":"SHAMELSMS Username","api_secret_key":"SHAMELSMS Password","sender":"SHAMELSMS ApiId"}','description' => 'SHAMELSMS','status' => '1','environment' => NULL),
            array('name' => 'INFOBIP','params' => '{"api_key":"INFOBIP Username","api_secret_key":"INFOBIP Password"}','description' => 'INFOBIP','status' => '1','environment' => NULL),
            array('name' => 'TWWWIRELESS','params' => '{"api_key":"TWWWIRELESS Username","api_secret_key":"TWWWIRELESS Password","sender":"TWWWIRELESS Sender"}','description' => 'TWWWIRELESS','status' => '1','environment' => NULL),
            array('name' => 'SMS123','params' => '{"api_key":"SMS123 Api Key","sender":"SMS123 Company Name"}','description' => 'SMS123','status' => '1','environment' => NULL),
            array('name' => 'BULKSMS','params' => '{"api_key":"BULKSMS Username","api_secret_key":"BULKSMS Password"}','description' => 'BULKSMS','status' => '1','environment' => NULL),
            array('name' => 'TEXTINGHOUSE','params' => '{"api_key":"TEXTINGHOUSE Username","api_secret_key":"TEXTINGHOUSE Password"}','description' => 'TEXTINGHOUSE','status' => '1','environment' => NULL),
            array('name' => 'MOBILE360','params' => '{"api_key":"Mobile360 Username","api_secret_key":"Mobile360 Password","sender":"Mobile360 Shote Code Mask"}','description' => 'Mobile360','status' => '1','environment' => NULL),
            array('name' => 'FACILITA_MOVEL','params' => '{"api_key":"FACILITA_MOVEL Username","api_secret_key":"FACILITA_MOVEL Password"}','description' => 'FACILITA_MOVEL','status' => '1','environment' => NULL),
            array('name' => 'E_SMS','params' => '{"api_key":"E_SMS Api key","api_secret_key":"E_SMS Secret Key","sender":"E_SMS Brand name"}','description' => 'E_SMS','status' => '1','environment' => NULL),
            array('name' => 'INFOBIP_SMS','params' => '{"api_key":"INFOBIP_SMS Api key","api_secret_key":"INFOBIP_SMS Base url","sender":"INFOBIP_SMS Sender"}','description' => 'INFOBIP_SMS','status' => '1','environment' => NULL),
            array('name' => 'iSmart','params' => '{"api_key":"User Id","api_secret_key":"Password"}','description' => 'iSmart','status' => '1','environment' => NULL),
            array('name' => 'smsportal','params' => '{"api_key":"Client ID","api_secret_key":"API Secret"}','description' => 'smsportal smsworx','status' => '1','environment' => NULL),
            array('name' => 'ArkeselSMS','params' => '{"api_key":"Api Key","sender":"Sender"}','description' => 'ArkeselSMS','status' => '1','environment' => NULL),
            array('name' => 'BurstSMS','params' => '{"api_key":"Api Key","sender":"Sender"}','description' => 'BurstSMS','status' => '1','environment' => NULL),
            array('name' => 'SMSBOX','params' => '{"api_key":"SMSBOX UserName","api_secret_key":"SMSBOX Password","account_id":"SMSBOX Gateway Id","sender":"SMSBOX Sender Name"}','description' => 'SMSBOX','status' => '1','environment' => '1'),
            array('name' => 'WhatsAppTodo','params' => NULL,'description' => 'WhatsAppTodo','status' => '1','environment' => '1'),
            array('name' => 'mymobileapi','params' => '{"api_key":"Client ID","api_secret_key":"API Secret"}','description' => 'mymobileapi smsworx','status' => '1','environment' => NULL),
            array('name' => 'SMSCTP','params' => '{"api_key":"Username","api_secret_key":"Password","sender":"Originator/Sender"}','description' => 'SMSCTP','status' => '1','environment' => NULL),
            array('name' => 'SMSDEV','params' => '{"api_key":"Api Key"}','description' => 'SMSDEV','status' => '1','environment' => NULL),
            array('name' => 'MUTHOFUN','params' => '{"api_key":"Username","api_secret_key":"Password"}','description' => 'MUTHOFUN','status' => '1','environment' => NULL),
            array('name' => 'KINGSMS','params' => '{"api_key":"Username","api_secret_key":"Token"}','description' => 'KINGSMS','status' => '1','environment' => NULL),
            array('name' => 'GLOBELABS','params' => '{"api_key":"App Id","api_secret_key":"App Secret","sender_number":"Short Code","auth_token":"Pass Phrase"}','description' => 'GLOBELABS','status' => '1','environment' => NULL),
            array('name' => 'MULTITEXTERSMS','params' => '{"api_key":"Email","api_secret_key":"Password","sender":"Sender Name Of Your Choice"}','description' => 'MULTITEXTERSMS','status' => '1','environment' => NULL),
            array('name' => 'SMSPRO_NIKITA','params' => '{"api_key":"User Name","api_secret_key":"Password","sender":"Sender Name Of Your Choice"}','description' => 'SMSPRO_NIKITA','status' => '1','environment' => NULL),
            array('name' => 'MESSAGEBIRD','params' => '{"api_key":"Access Token","sender":"Sender Name Of Your Choice(Project\'s name)"}','description' => 'Message Bird','status' => '1','environment' => NULL),
            array('name' => 'FLOPPYSEND','params' => '{"api_key":"Api Key","sender":"Sender Name Of Your Choice(Project name)"}','description' => 'Floppy Send','status' => '1','environment' => NULL),
            array('name' => 'RICHCOMMUNICATION','params' => '{"api_secret_key":"Auth Key","sender":"Sender Id"}','description' => 'Rich Communication','status' => '1','environment' => NULL),
            array('name' => 'SMSTO','params' => '{"api_secret_key":"Api Key","sender":"Sender Name"}','description' => 'SMS To','status' => '1','environment' => NULL),
            array('name' => 'TELESOM','params' => '{"api_key":"User Name","api_secret_key":"Password","sender":"Sender","auth_token":"Key"}','description' => 'My Telesom','status' => '1','environment' =>NULL),
            array('name' => 'SUDACELLBULKSMS','params' => '{"api_key":"User Name","api_secret_key":"Password","sender":"Sender"}','description' => 'SUDACELLBULKSMS','status' => '1','environment' =>NULL),
            array('name' => 'TELESOM','params' => '{"api_key":"User Name","api_secret_key":"Password","sender":"Sender","auth_token":"Key"}','description' => 'My Telesom','status' => '1','environment' => NULL),
            array('name' => 'BULKSMSSERVICES','params' => '{"api_key":"User Name","api_secret_key":"Password","sender":"Sender"}','description' => 'BulkSMSServices','status' => '1','environment' => NULL),
            array('name' => 'ORANGESMS','params' => '{"api_key":"ORANGESMS SenderAddress","sender":"ORANGESMS sender","auth_token":"ORANGESMS AuthToken"}','description' => 'ORANGESMS','status' => '1','environment' => NULL),
            array('name' => 'CLICKSEND','params' => '{"api_key":"User Name","api_secret_key":"Api Key"}','description' => 'ClickSend','status' => '1','environment' => NULL),
            array('name' => 'SINCH','params' => '{"api_key":"Service Plan Id","api_secret_key":"Bearer Token","sender":"Virtual Number"}','description' => 'Sinch','status' => '1','environment' => NULL),
            array('name' => 'SMSBUS','params' => '{"api_key":"Username","api_secret_key":"Password","sender":"Sender"}','description' => 'SmsBus','status' => '1','environment' => NULL),
            array('name' => 'NIGERIABULKSMS','params' => '{"api_key":"Username","api_secret_key":"Password","sender":"Sender"}','description' => 'nigeriabulksms','status' => '1','environment' => NULL),
            array('name' => 'MESSAGEMEDIA','params' => '{"api_key":"Api Key","api_secret_key":"Api Secret"}','description' => 'MessageMedia','status' => '1','environment' => NULL),
            array('name' => 'ORANGESMSPRO','params' => '{"api_key":"OrangeSMSPro Username","api_secret_key":"OrangeSMSPro Private Key","auth_token":"OrangeSMSPro Token","sender":"OrangeSMSPro Subject","subacct":"OrangeSMSPro Signature"}','description' => 'OrangeSMSPro','status' => '1','environment' => NULL),
            array('name' => 'SMSZEDEKAA','params' => '{"api_key":"SmsZedekaa ApiKey","api_secret_key":"SmsZedekaa ClientId","sender":"SmsZedekaa SenderId"}','description' => 'SmsZedekaa','status' => '1','environment' => NULL),
            array('name' => 'NOTIFY','params' => '{"api_key":"User ID","api_secret_key":"Api Key","sender":"Sender"}','description' => 'App Notify Lk','status' => '1','environment' => NULL),
            array('name' => 'NIGERIABULKSMS','params' => '{"api_key":"Username","api_secret_key":"Password","sender":"Sender"}','description' => 'nigeriabulksms','status' => '1','environment' => NULL),
            array('name' => 'MESSAGEMEDIA','params' => '{"api_key":"Api Key","api_secret_key":"Api Secret"}','description' => 'MessageMedia','status' => '1','environment' => NULL),
            array('name' => 'ORANGESMSPRO','params' => '{"api_key":"OrangeSMSPro Username","api_secret_key":"OrangeSMSPro Private Key","auth_token":"OrangeSMSPro Token","sender":"OrangeSMSPro Subject","subacct":"OrangeSMSPro Signature"}','description' => 'OrangeSMSPro','status' => '1','environment' => NULL),
            array('name' => 'SMSZEDEKAA','params' => '{"api_key":"SmsZedekaa ApiKey","api_secret_key":"SmsZedekaa ClientId","sender":"SmsZedekaa SenderId"}','description' => 'SmsZedekaa','status' => '1','environment' => NULL),
            array('name' => 'BEEMAFRICA','params' => '{"api_key":"BeemAfrica Api Key","api_secret_key":"BeemAfrica Secret Key"}','description' => 'BeemAfrica','status' => '1','environment' => NULL),
            array('name' => 'MULTITEXTER_V2','params' => '{"api_key":"MultiTexterV2 Api Key","sender":"MultiTexterV2 SenderId"}','description' => 'MultiTexterV2','status' => '1','environment' => NULL),
            array('name' => 'LINXSMS','params' => '{"api_key":"5LinxSms Username","api_secret_key":"5LinxSms Password","sender":"5LinxSms SenderId"}','description' => '5LinxSms','status' => '1','environment' => NULL),
            array('name' => 'BULKSMSDHIRAAGU','params' => '{"api_key":"BulkSMSDhiraagu Username","api_secret_key":"BulkSMSDhiraagu Password"}','description' => 'BulkSMSDhiraagu','status' => '1','environment' => NULL),
            array('name' => 'CLOUDWEBSMS','params' => '{"api_key":"CloudWebSMS Api Key","api_secret_key":"CloudWebSMS Password","sender":"CloudWebSMS SenderId"}','description' => 'CloudWebSMS','status' => '1','environment' => NULL),
            array('name' => 'SMSPOH','params' => '{"api_secret_key":"SMSPoh Api Ke","sender":"SMSPoh SenderId"}','description' => 'SMSPoh','status' => '1','environment' => NULL),
            array('name' => 'CMTELECOME','params' => '{"api_secret_key":"Api token","sender":"SMS SenderId"}','description' => 'cmtelecom','status' => '1','environment' => NULL),
            array('name' => 'GEEZSMS', 'params' => '{"api_secret_key":"Api token","sender":"ShortCode"}', 'description' => 'GeezSMS', 'status' => '1', 'environment' => NULL,),
            array('name' => 'BULKSMSPLANS','params' => '{"api_key":"API Id","api_secret_key":"Api Password","sender":"Sender","sender_number":"Template Id"}','description' => 'BulkSMSPlans','status' => '1','environment' => NULL),
            array('name' => 'WEBLINE','params' => '{"auth_token":"API Token","sender":"Sender"}','description' => 'WEBLINE','status' => '1','environment' => NULL),
            array('name' => 'SMSTEKNIK','params' => '{"api_key":"Teknik Username","api_secret_key":"Teknik Password","sender":"Company"}','description' => 'SMSTeknik','status' => '1','environment' => NULL),
            array('name' => 'INTOUCHSMS','params' => '{"api_key":"Username","api_secret_key":"Password","sender":"Sender"}','description' => 'IntouchSMS','status' => '1','environment' => NULL),
            array('name' => 'NALOSOLUTIONSMS','params' => '{"api_key":"Username","api_secret_key":"Password","sender":"Sender Id"}','description' => 'NaloSolutionsSMS','status' => '1','environment' => NULL),
            array('name' => 'TWILIO_WHATSAPP','params' => '{"api_key":"Twilio SID","api_secret_key":"Twilio AuthToken","sender":"Twilio Whatsapp Number"}','description' => 'Twilio Whatsapp','status' => '1','environment' => NULL),
            array('name' => 'TERMII','params' => '{"api_key":"TERMII API KEY","sender":"Sender"}','description' => 'Termii','status' => '1','environment' => NULL),
            array('name' => 'MOBIWEB','params' => '{"api_key":"MOBIWEB Username","api_secret_key":"Mobiweb Password","sender":"Sender"}','description' => 'MOBIWEB','status' => '1','environment' => NULL),
            array('name' => 'SMS_ETHIOPIA','params' => '{"auth_token":"API URL","api_key":"Api Username","api_secret_key":"Api Password"}','description' => 'SMS Ethiopia','status' => '1','environment' => NULL),
            array('name' => 'ETECH','params' => '{"api_key":"Api Username","api_secret_key":"Api Password","sender":"Sender"}','description' => 'eTech','status' => '1','environment' => NULL),
            array('name' => 'ADERASMS','params' => '{"api_key":"User Name","api_secret_key":"Password"}','description' => 'For Adera client','status' => '1','environment' =>NULL),
            array('name' => 'NEXTSMS','params' => '{"api_key":"NextSMS Username","api_secret_key":"NextSMS Password","sender":"Sender"}','description' => 'NextSMS','status' => '1','environment' => NULL),
            array('name' => 'SMSONFONMEDIA','params' => '{"api_key":"Api Key","api_secret_key":"Client Id","sender":"Sender"}','description' => 'SMSOnfonMedia','status' => '1','environment' => NULL),
            array('name' => 'ZOOMCONNECT','params' => '{"api_key":"Email","api_secret_key":"Token"}','description' => 'ZoomConnect','status' => '1','environment' => NULL),
            array('name' => 'VONAGE_SMS','params' => '{"api_key":"Api Key","api_secret_key":"Api Secret","sender":"Sender"}','description' => 'Vonage SMS Gateway','status' => '1','environment' =>NULL),
            array('name' => 'TCAST_SMS','params' => '{"api_key":"Api Key","api_secret_key":"Client ID","sender":"Sender ID"}','description' => 'TCast SMS','status' => '1','environment' =>NULL),
            array('name' => 'ZOOMCONNECT','params' => '{"api_secret_key":"Secret Key"}','description' => 'ZoomConnect','status' => '1','environment' => NULL),
            array('name' => 'SMSUEHTP','params' => '{"api_key":"Username","api_secret_key":"Password"}','description' => 'SmsUEHTP','status' => '1','environment' => NULL),
            array('name' => 'TELESIGN','params' => '{"api_key":"Customer Id","api_secret_key":"Api Key"}','description' => 'TeleSign','status' => '1','environment' => NULL),
            array('name' => 'HADARABULKSMS','params' => '{"api_secret_key":"Api Key"}','description' => 'HadaraBulkSMS','status' => '1','environment' => NULL),
            array('name' => 'M_NOTIFY','params' => '{"api_key":"Api Key","sender":"Sender"}','description' => 'mNotify','status' => '1','environment' => NULL),
            array('name' => 'WASSA_SMS','params' => '{"api_key":"Token","sender":"Sender"}','description' => 'WassaSMS','status' => '1','environment' => NULL),
            array('name' => 'SMSARKESEL','params' => '{"api_key":"Api Key","sender":"Sender"}','description' => 'SmsArkesel','status' => '1','environment' => NULL,'created_at' => '2022-12-23 16:47:09','updated_at' => '2022-12-23 16:47:09'),
            array('name' => 'SMSHUB','params' => '{"api_key":"Auth Id","api_secret_key":"Secret Key"}','description' => 'SMSHub','status' => '1','environment' => NULL),
            array('name' => 'LE_TEXTO','params' => '{"api_key":"Api Username","api_secret_key":"Api Password","sender":"Sender"}','description' => 'LeTexto','status' => '1','environment' => NULL),
            array('name' => 'SMARTVISION','params' => '{"api_key":"Api Key","sender":"Sender ID"}','description' => 'SmartVision','status' => '1','environment' => NULL),
            array('name' => 'UNIMATRIX','params' => '{"api_key":"Access Key","sender":"Sender ID","auth_token":"Template Content"}','description' => 'Unimatrix','status' => '1','environment' => NULL),
            array('name' => 'RELEANS','params' => '{"auth_token":"API Key","sender":"Sender ID"}','description' => 'Releans','status' => '1','environment' => NULL),
            array('name' => 'M_TARGET','params' => '{"api_key":"Username","api_secret_key":"Password","sender":"Sender","auth_token":"ServiceId"}','description' => 'mTarget','status' => '1','environment' => NULL),
            array('name' => 'YEGARA','params' => '{"api_key":"Username","api_secret_key":"Password"}','description' => 'Yegara','status' => '1','environment' => NULL),
            array('name' => 'NITEXT','params' => '{"api_key":"Username","api_secret_key":"Password","sender":"Sender"}','description' => 'NiText','status' => '1','environment' => NULL),
            array('name' => 'ZYNLE','params' => '{"api_key":"Username","api_secret_key":"Password","sender":"Sender"}','description' => 'ZYNLE','status' => '1','environment' => NULL),
            array('name' => 'HORMUUD','params' => '{"api_key":"Username","api_secret_key":"Password","sender":"Sender"}','description' => 'HORMUUD','status' => '1','environment' => NULL),
            array('name' => 'NATYABIP','params' => '{"api_key":"Username","api_secret_key":"Password","sender":"Sender"}','description' => 'NATYABIP','status' => '1','environment' => NULL),
            array('name' => 'ARKESEL','params' => '{"api_key":"Username","api_secret_key":"Password","sender":"Sender"}','description' => 'Arkesel','status' => '1','environment' => NULL),
            array('name' => 'KWIKTALKSMS','params' => '{"api_key":"Api key","auth_token":"Authorization Token","sender":"Sender"}','description' => 'Kwiktalk','status' => '1','environment' => NULL),
            array('name' => 'ET_DELIVERY_SMS','params' => '{"api_secret_key":"Base url"}','description' => 'EtDeliverySMS','status' => '1','environment' => NULL),
            array('name' => 'MSGOWLSMS','params' => '{"api_key":"Api key","sender":"Sender"}','description' => 'MsgOwl','status' => '1','environment' => NULL),
            array('name' => 'SMSMASIVOS','params' => '{"api_secret_key":"Security key"}','description' => 'smsmasivos','status' => '1','environment' => NULL),
            array('name' => 'SMSD7','params' => '{"api_secret_key":"Security key","sender":"Sender Id"}','description' => 'SMSD7','status' => '1','environment' => NULL),
            array('name' => 'SMSTRANZAK','params' => '{"api_secret_key":"App key","api_public_key":"App Id"}','description' => 'SMSTRANZAK','status' => '1','environment' => NULL),
            array('name' => 'MTARGETSMS','params' => '{"api_secret_key":"Password","api_public_key":"Username","sender":"Sender"}','description' => 'MTARGETSMS','status' => '1','environment' => NULL),
            array('name' => 'TERMIISMS','params' => '{"api_key":"Api Key","sender":"Sender"}','description' => 'TERMIISMS','status' => '1','environment' => NULL),
            array('name' => 'TEXTSMS','params' => '{"api_key":"Player Id","api_secret_key":"Api Key","sender":"Sender"}','description' => 'TEXTSMS','status' => '1','environment' => NULL),
            array('name' => 'ISMS','params' => '{"api_key":"Partner Id","api_secret_key":"Api Key","sender":"Short Code"}','description' => 'ISMS','status' => '1','environment' => NULL),
            array('name' => 'TELESIGNSMS','params' => '{"api_key":"Customer Id","api_secret_key":"Api Key"}','description' => 'TELESIGNSMS','status' => '1','environment' => NULL),
            array('name' => 'SMSALERT','params' => '{"api_key":"Api Key","sender":"Sender Id"}','description' => 'SMSALERT','status' => '1','environment' => NULL),
            array('name' => 'CHEVNI_SMS','params' => '{"sender_number":"Sender Id"}','description' => 'CHEVNI_SMS','status' => '1','environment' => NULL),
            array('name' => 'WHATSAPP_GATEWAY','params' => '{"auth_token":"Token","sender":"Sender Id"}','description' => 'WHATSAPP_GATEWAY','status' => '1','environment' => NULL),
            array('name' => 'DREAM_DIGTAL','params' => '{"api_key": "API Id","auth_token":"API Password","sender":"Sender Id"}','description' => 'DREAM_DIGTAL','status' => '1','environment' => NULL),
            array('name' => 'SAMAYA_SMS','params' => '{"api_key": "API Key","sender":"Sender Id"}','description' => 'SAMAYA_SMS','status' => '1','environment' => NULL),
            array('name' => 'WIREPICK','params' => '{"api_key": "Client","sender":"Sender Id", "auth_token":"Password"}','description' => 'WIREPICK','status' => '1','environment' => NULL),
            array('name' => 'TEXTMAGIC','params' => '{"api_key": "Api Key","auth_token":"Username"}','description' => 'TEXTMAGIC','status' => '1','environment' => NULL),
            array('name' => 'TILILTECH','params' => '{"api_key": "Api Key","sender":"Short Code"}','description' => 'TILILTECH','status' => '1','environment' => NULL),
            array('name' => 'HUD_HUD_SMS','params' => '{"api_key": "Username","api_secret_key":"Password"}','description' => 'HUDHUDSMS','status' => '1','environment' => NULL),
            array('name' => 'SPEEDA_MOBILE','params' => '{"api_key": "Api Id","api_secret_key":"Api Password","sender":"Sender Id"}','description' => 'SPEEDAMOBILE','status' => '1','environment' => NULL),
            array('name' => 'KUDISMS','params' => '{"api_key": "Api Key","sender":"Sender Id"}','description' => 'KUDISMS','status' => '1','environment' => NULL),
            array('name' => 'TWILLIO_MESSAGE_SERVICE','params' => '{"api_key":"SID","sender":"Message Service sid","auth_token":"Auth Token"}','description' => 'twillio','status' => '1','environment' => NULL),
            array('name' => 'DEXATEL','params' => '{"api_key":"Secret Key","sender":"Sender Id"}','description' => 'Dexatel','status' => '1','environment' => NULL),
            array('name' => 'AQILAS','params' => '{"api_key":"X-AUTH-TOKEN","sender":"Any sender name"}','description' => 'www.aqilas.com','status' => '1','environment' => NULL),
            array('name' => 'TERMII_V3_LATEST','params' => '{"api_key":"Secret Key","api_secret_key":"Base url",,"sender":"Sender Id"}','description' => 'TERMII_V3','status' => '1','environment' => NULL),
            array('name' => 'WIN_SMS','params' => '{"api_key":"UserName","api_secret_key":"Pasword""}','description' => 'WIN_SMS','status' => '1','environment' => NULL),
            array('name' => 'XWIRELESS','params' => '{"api_key":"Api Key","api_secret_key":"Client Id","sender":"Sender Id"}','description' => 'XWIRELESS','status' => '1','environment' => NULL),
            array('name' => 'NEXAH_SMSVAS','params' => '{"api_key":"UserName","api_secret_key":"Pasword","sender":"Sender Id"}','description' => 'NEXAH_SMSVAS','status' => '1','environment' => NULL),
            array('name' => 'EASYDIGITALSMS','params' => '{"api_key":"Api Key","sender":"Sender Id"}','description' => 'EASYDIGITALSMS/EDSMS','status' => '1','environment' => NULL),
            array('name' => 'MTSMS','params' => '{"api_key":"Authorization Token","sender":"Sender Id"}','description' => 'MTSMS','status' => '1','environment' => NULL),
            array('name' => 'AFOMESS_SMS','params' => '{"api_secret_key":"Authorization Token","sender":"Sender Id"}','description' => 'AFOMESS_SMS','status' => '1','environment' => NULL),
            array('name' => '360nrs_SMS','params' => '{"api_key":"UserName","api_secret_key":"Pasword","sender":"Sender Id"}','description' => 'SMS_360nrs','status' => '1','environment' => NULL),
            array('name' => 'Textlk_SMS','params' => '{"api_secret_key":"Bearer Api Key","sender":"Sender Id"}','description' => 'Textlk_SMS','status' => '1','environment' => NULL),
            array('name' => 'Bulk_Messaging_Gateway','params' => '{"api_key":"UserName","api_secret_key":"Pasword","sender":"Sender Id"}','description' => 'bulk_messaging_gateway','status' => '1','environment' => NULL),
            array('name' => 'CLARION_SMS','params' => '{"api_secret_key":"Authorization Token","sender":"Sender Id"}','description' => 'CLARION_SMS','status' => '1','environment' => NULL),
            array('name' => 'FASTHUB_SMS','params' => '{"api_key":"Client Id","api_secret_key":"Client Secret","sender":"SenderId/Source"}','description' => 'FASTHUB_SMS','status' => '1','environment' => NULL),
            array('name' => 'TELCOMW_SMS','params' => '{"api_key":"Api Key","api_secret_key":"Password","sender":"SenderId"}','description' => 'TELCOMW_SMS','status' => '1','environment' => NULL),
            array('name' => 'EVERLYTIC_SMS','params' => '{"api_key":"User Name","api_secret_key":"Password/Api Key","auth_token":"Base Url"}','description' => 'EVERLYTIC_SMS','status' => '1','environment' => NULL),
            array('name' => 'AWS_SMS','params' => '{"api_key":"Api Key","api_secret_key":"Secret Key","auth_token":"Region"}','description' => 'AWS_SMS','status' => '1','environment' => NULL),
            array('name' => 'AUTHENTICA_SMS','params' => '{"api_key":"Api Key"}','description' => 'AUTHENTICA_SMS','status' => '1','environment' => NULL),
            array('name' => 'SMSFLOW','params' => '{"api_key":"Client Id","api_secret_key":"Client Secret Key"}','description' => 'SMSFLOW','status' => '1','environment' => NULL),
            array('name' => 'BLUEDOT_SMS','params' => '{"api_key":"Api Id","api_secret_key":"Api Passowrd","sender":"SenderId"}','description' => 'BLUEDOT_SMS','status' => '1','environment' => NULL),
            array('name' => 'MOZE_SMS','params' => '{"api_key":"Api/Bearer Key","sender":"SenderId"}','description' => 'MOZE_SMS','status' => '1','environment' => NULL),
            array('name' => 'NGHCORP_SMS','params' => '{"api_key":"Api Key","sender":"SenderId","api_secret_key":"Api Secret"}','description' => 'NGHCORP_SMS','status' => '1','environment' => NULL),
            array('name' => 'ILETIMX_SMS','params' => '{"api_key":"UserName","sender":"Originator","api_secret_key":"Password"}','description' => 'NGHCORP_SMS','status' => '1','environment' => NULL),
            array('name' => 'APIARY_FDI_SMS','params' => '{"api_key":"UserName","sender":"Sender","api_secret_key":"Password"}','description' => 'APIARY_FDI_SMS','status' => '1','environment' => NULL),
            array('name' => 'AVRSMS','params' => '{"api_key":"Api Id","sender":"Sender","api_secret_key":"Api Password"}','description' => 'AVRSMS','status' => '1','environment' => NULL),
            array('name' => 'DIALOG_SMS','params' => '{"api_key":"UserName","sender":"Sender","api_secret_key":"Password"}','description' => 'DIALOG_SMS','status' => '1','environment' => NULL),
            array('name' => 'YEGNATELE_SMS','params' => '{"api_key":"AccountId","sender":"codeId","api_secret_key":"Api Token"}','description' => 'YEGNATELE_SMS','status' => '1','environment' => NULL),            
            array('name' => 'SPRINT_SMS','params' => '{"api_key":"Api Id","sender":"sender_id","api_secret_key":"Api Password"}','description' => 'SPRINT_SMS','status' => '1','environment' => NULL),
            array('name' => 'EXPRESSO_SMS','params' => '{"api_key":"Username","sender":"Sender","api_secret_key":"Password"}','description' => 'EXPRESSO_SMS','status' => '1','environment' => NULL),
            array('name' => 'TSEMBA_SMS','params' => '{"api_key":"Api Key","sender":"SenderId"}','description' => 'TSEMBA_SMS','status' => '1','environment' => NULL),
            array('name' => 'TXT_SMS','params' => '{"api_key":"Username","sender":"Sender","api_secret_key":"Password"}','description' => 'TXT_SMS','status' => '1','environment' => NULL),
            );
        foreach($sms_gateways as $gateway){
            \App\Models\SmsGateways::create(array_merge($gateway, array("created_at" => Carbon::now(), "updated_at" => Carbon::now())));
        }
    }
}
