<?php
/**
 * Created by PhpStorm.
 * User: apporio
 * Date: 13/1/23
 * Time: 5:02 PM
 */

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Laravel\Passport\HasApiTokens;

class GuestUser extends Model
{
    use HasApiTokens, Notifiable;

    protected $table = "users";

    protected $guarded = [];

    protected static function boot()
    {
        parent::boot();
        static::creating(function ($model) {
            $model->user_merchant_id = $model->NewUserId($model->merchant_id);
            return $model;
        });
    }

    public function NewUserId($merchantID)
    {
        $user = User::where([['merchant_id', '=', $merchantID]])->latest()->first();
        if (!empty($user)) {
            return $user->user_merchant_id + 1;
        } else {
            return 1;
        }
    }

    public function newQuery($excludeDeleted = true)
    {
        return parent::newQuery($excludeDeleted)->where("is_guest",1); // TODO: Change the autogenerated stub
    }
}
